# PERCENTAGE UP TO 100
# Example: 1 = 1%
spawning-chance: 1
# List of surfaces:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# spawnable-surfaces: [] # To set on all surfaces
spawnable-surfaces:
  - PURPUR_BLOCK
# Surfaces blacklist same as above
spawnable-surfaces-blacklist: []
# Should break the block under it after spawning?
break-surface-on-spawn: false